export enum AssetTags {
  permissioned = "permissioned",
  yieldBearingToken = "yield",
  stablecoin = "stablecoin",
  usd = "usd-pegged",
  eur = "eur-pegged",
  btc = "btc",
  eth = "eth",
  erc4626 = "erc4626",
  lst = "lst",
  lrt = "lrt",
  rwa = "rwa",
  hardcoded = "hardcoded",
  convex = "convex-wrapper",
  governance = "governance-token",
  permit = "simple-permit",
  permitDai = "dai-specific-permit",
}
