checksumBehavior: update

yarnPath: .yarn/releases/yarn-4.4.1.cjs

packageExtensions:
  "@wagmi/core@*":
    dependencies:
      "@tanstack/query-core": "*"
  "wagmi@*":
    dependencies:
      "@tanstack/query-core": "*"