packages:
  - packages/*

overrides:
  '@babel/helpers': 7.29.2
  '@graphql-codegen/client-preset': 5.2.4
  ajv: 8.18.0
  axios: 1.15.0
  flatted: 3.4.2
  follow-redirects: 1.16.0
  handlebars: 4.7.9
  js-yaml: 4.1.1
  lodash: 4.18.1
  micromatch>picomatch: 2.3.2
  postcss: 8.5.12
  read-yaml-file: 2.1.0
  rollup: 4.60.1
  tinyglobby>picomatch: 4.0.4
  tmp: 0.2.4
  undici: 6.24.1
  vite: 8.0.8
  vitest>picomatch: 4.0.4
  yaml: 2.8.3

onlyBuiltDependencies:
  - '@biomejs/biome'
  - bufferutil
  - esbuild
  - keccak
  - secp256k1
  - utf-8-validate

allowBuilds:
  bufferutil: true
  utf-8-validate: true
