export {
  BlueErrors,
  DivisionByZeroError,
  IncompleteChainRegistryError,
  InvalidAddressError,
  InvalidBitLengthError,
  InvalidMarketParamsError,
  RegistryValueAlreadyRegisteredError,
  UnknownAddressError,
  UnknownDataError,
  UnknownFactory,
  UnknownMarketAllocationError,
  UnknownMarketParamsError,
  UnknownOfFactory,
  UnknownTokenError,
  UnknownTokenPriceError,
  UnknownVaultConfigError,
  UnsupportedChainIdError,
  UnsupportedMarketIrmError,
  /** @deprecated Pre-liquidation support is deprecated and will be removed in the next major. */
  UnsupportedPreLiquidationParamsError,
  UnsupportedVaultV2AdapterError,
  VaultV2Errors,
} from "@morpho-org/blue-sdk";
export {
  AbiFunctionNotFoundError,
  getUnsupportedVaultV2Adapter,
  InvalidNumberError,
  InvalidPermitDomainChainIdError,
  InvalidPermitDomainVerifyingContractError,
  isUnknownOfFactoryError,
  MarketParamsIdMismatchError,
  NonTupleReturnValueError,
  UnnamedAbiOutputsError,
  UnsupportedPermitDomainExtensionsError,
} from "@morpho-org/blue-sdk-viem";
