/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  AddressLike,
  BaseContract,
  BigNumberish,
  BytesLike,
  ContractMethod,
  ContractRunner,
  EventFragment,
  FunctionFragment,
  Interface,
  Listener,
  Result,
} from "ethers";
import type {
  TypedContractEvent,
  TypedContractMethod,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedLogDescription,
} from "./common";

export interface CurveStableSwapNGInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "exchange(int128,int128,uint256,uint256)"
      | "exchange(int128,int128,uint256,uint256,address)"
      | "exchange_received(int128,int128,uint256,uint256)"
      | "exchange_received(int128,int128,uint256,uint256,address)"
      | "add_liquidity(uint256[],uint256)"
      | "add_liquidity(uint256[],uint256,address)"
      | "remove_liquidity_one_coin(uint256,int128,uint256)"
      | "remove_liquidity_one_coin(uint256,int128,uint256,address)"
      | "remove_liquidity_imbalance(uint256[],uint256)"
      | "remove_liquidity_imbalance(uint256[],uint256,address)"
      | "remove_liquidity(uint256,uint256[])"
      | "remove_liquidity(uint256,uint256[],address)"
      | "remove_liquidity(uint256,uint256[],address,bool)"
      | "withdraw_admin_fees"
      | "last_price"
      | "ema_price"
      | "get_p"
      | "price_oracle"
      | "D_oracle"
      | "transfer"
      | "transferFrom"
      | "approve"
      | "permit"
      | "DOMAIN_SEPARATOR"
      | "get_dx"
      | "get_dy"
      | "calc_withdraw_one_coin"
      | "totalSupply"
      | "get_virtual_price"
      | "calc_token_amount"
      | "A"
      | "A_precise"
      | "balances"
      | "get_balances"
      | "stored_rates"
      | "dynamic_fee"
      | "ramp_A"
      | "stop_ramp_A"
      | "set_new_fee"
      | "set_ma_exp_time"
      | "N_COINS"
      | "coins"
      | "fee"
      | "offpeg_fee_multiplier"
      | "admin_fee"
      | "initial_A"
      | "future_A"
      | "initial_A_time"
      | "future_A_time"
      | "admin_balances"
      | "ma_exp_time"
      | "D_ma_time"
      | "ma_last_time"
      | "name"
      | "symbol"
      | "decimals"
      | "version"
      | "balanceOf"
      | "allowance"
      | "nonces"
      | "salt",
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Transfer"
      | "Approval"
      | "TokenExchange"
      | "TokenExchangeUnderlying"
      | "AddLiquidity"
      | "RemoveLiquidity"
      | "RemoveLiquidityOne"
      | "RemoveLiquidityImbalance"
      | "RampA"
      | "StopRampA"
      | "ApplyNewFee"
      | "SetNewMATime",
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "exchange(int128,int128,uint256,uint256)",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "exchange(int128,int128,uint256,uint256,address)",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: "exchange_received(int128,int128,uint256,uint256)",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "exchange_received(int128,int128,uint256,uint256,address)",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: "add_liquidity(uint256[],uint256)",
    values: [BigNumberish[], BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "add_liquidity(uint256[],uint256,address)",
    values: [BigNumberish[], BigNumberish, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity_one_coin(uint256,int128,uint256)",
    values: [BigNumberish, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity_one_coin(uint256,int128,uint256,address)",
    values: [BigNumberish, BigNumberish, BigNumberish, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity_imbalance(uint256[],uint256)",
    values: [BigNumberish[], BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity_imbalance(uint256[],uint256,address)",
    values: [BigNumberish[], BigNumberish, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity(uint256,uint256[])",
    values: [BigNumberish, BigNumberish[]],
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity(uint256,uint256[],address)",
    values: [BigNumberish, BigNumberish[], AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity(uint256,uint256[],address,bool)",
    values: [BigNumberish, BigNumberish[], AddressLike, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw_admin_fees",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "last_price",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "ema_price",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "get_p", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "price_oracle",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "D_oracle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "permit",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "get_dx",
    values: [BigNumberish, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "get_dy",
    values: [BigNumberish, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "calc_withdraw_one_coin",
    values: [BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "get_virtual_price",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "calc_token_amount",
    values: [BigNumberish[], boolean],
  ): string;
  encodeFunctionData(functionFragment: "A", values?: undefined): string;
  encodeFunctionData(functionFragment: "A_precise", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "get_balances",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "stored_rates",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "dynamic_fee",
    values: [BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "ramp_A",
    values: [BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "stop_ramp_A",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "set_new_fee",
    values: [BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "set_ma_exp_time",
    values: [BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "N_COINS", values?: undefined): string;
  encodeFunctionData(functionFragment: "coins", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "offpeg_fee_multiplier",
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: "admin_fee", values?: undefined): string;
  encodeFunctionData(functionFragment: "initial_A", values?: undefined): string;
  encodeFunctionData(functionFragment: "future_A", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initial_A_time",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "future_A_time",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "admin_balances",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "ma_exp_time",
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: "D_ma_time", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ma_last_time",
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike],
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "salt", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "exchange(int128,int128,uint256,uint256)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "exchange(int128,int128,uint256,uint256,address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "exchange_received(int128,int128,uint256,uint256)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "exchange_received(int128,int128,uint256,uint256,address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_liquidity(uint256[],uint256)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_liquidity(uint256[],uint256,address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity_one_coin(uint256,int128,uint256)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity_one_coin(uint256,int128,uint256,address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity_imbalance(uint256[],uint256)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity_imbalance(uint256[],uint256,address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity(uint256,uint256[])",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity(uint256,uint256[],address)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity(uint256,uint256[],address,bool)",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdraw_admin_fees",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "last_price", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ema_price", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "get_p", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "price_oracle",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "D_oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "permit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "get_dx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "get_dy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calc_withdraw_one_coin",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_virtual_price",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "calc_token_amount",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "A", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "A_precise", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "get_balances",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "stored_rates",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "dynamic_fee",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "ramp_A", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stop_ramp_A",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "set_new_fee",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "set_ma_exp_time",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "N_COINS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "coins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "offpeg_fee_multiplier",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "admin_fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initial_A", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "future_A", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initial_A_time",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "future_A_time",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "admin_balances",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "ma_exp_time",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "D_ma_time", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ma_last_time",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "salt", data: BytesLike): Result;
}

export namespace TransferEvent {
  export type InputTuple = [
    sender: AddressLike,
    receiver: AddressLike,
    value: BigNumberish,
  ];
  export type OutputTuple = [sender: string, receiver: string, value: bigint];
  export interface OutputObject {
    sender: string;
    receiver: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish,
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenExchangeEvent {
  export type InputTuple = [
    buyer: AddressLike,
    sold_id: BigNumberish,
    tokens_sold: BigNumberish,
    bought_id: BigNumberish,
    tokens_bought: BigNumberish,
  ];
  export type OutputTuple = [
    buyer: string,
    sold_id: bigint,
    tokens_sold: bigint,
    bought_id: bigint,
    tokens_bought: bigint,
  ];
  export interface OutputObject {
    buyer: string;
    sold_id: bigint;
    tokens_sold: bigint;
    bought_id: bigint;
    tokens_bought: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenExchangeUnderlyingEvent {
  export type InputTuple = [
    buyer: AddressLike,
    sold_id: BigNumberish,
    tokens_sold: BigNumberish,
    bought_id: BigNumberish,
    tokens_bought: BigNumberish,
  ];
  export type OutputTuple = [
    buyer: string,
    sold_id: bigint,
    tokens_sold: bigint,
    bought_id: bigint,
    tokens_bought: bigint,
  ];
  export interface OutputObject {
    buyer: string;
    sold_id: bigint;
    tokens_sold: bigint;
    bought_id: bigint;
    tokens_bought: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddLiquidityEvent {
  export type InputTuple = [
    provider: AddressLike,
    token_amounts: BigNumberish[],
    fees: BigNumberish[],
    invariant: BigNumberish,
    token_supply: BigNumberish,
  ];
  export type OutputTuple = [
    provider: string,
    token_amounts: bigint[],
    fees: bigint[],
    invariant: bigint,
    token_supply: bigint,
  ];
  export interface OutputObject {
    provider: string;
    token_amounts: bigint[];
    fees: bigint[];
    invariant: bigint;
    token_supply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoveLiquidityEvent {
  export type InputTuple = [
    provider: AddressLike,
    token_amounts: BigNumberish[],
    fees: BigNumberish[],
    token_supply: BigNumberish,
  ];
  export type OutputTuple = [
    provider: string,
    token_amounts: bigint[],
    fees: bigint[],
    token_supply: bigint,
  ];
  export interface OutputObject {
    provider: string;
    token_amounts: bigint[];
    fees: bigint[];
    token_supply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoveLiquidityOneEvent {
  export type InputTuple = [
    provider: AddressLike,
    token_id: BigNumberish,
    token_amount: BigNumberish,
    coin_amount: BigNumberish,
    token_supply: BigNumberish,
  ];
  export type OutputTuple = [
    provider: string,
    token_id: bigint,
    token_amount: bigint,
    coin_amount: bigint,
    token_supply: bigint,
  ];
  export interface OutputObject {
    provider: string;
    token_id: bigint;
    token_amount: bigint;
    coin_amount: bigint;
    token_supply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoveLiquidityImbalanceEvent {
  export type InputTuple = [
    provider: AddressLike,
    token_amounts: BigNumberish[],
    fees: BigNumberish[],
    invariant: BigNumberish,
    token_supply: BigNumberish,
  ];
  export type OutputTuple = [
    provider: string,
    token_amounts: bigint[],
    fees: bigint[],
    invariant: bigint,
    token_supply: bigint,
  ];
  export interface OutputObject {
    provider: string;
    token_amounts: bigint[];
    fees: bigint[];
    invariant: bigint;
    token_supply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RampAEvent {
  export type InputTuple = [
    old_A: BigNumberish,
    new_A: BigNumberish,
    initial_time: BigNumberish,
    future_time: BigNumberish,
  ];
  export type OutputTuple = [
    old_A: bigint,
    new_A: bigint,
    initial_time: bigint,
    future_time: bigint,
  ];
  export interface OutputObject {
    old_A: bigint;
    new_A: bigint;
    initial_time: bigint;
    future_time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StopRampAEvent {
  export type InputTuple = [A: BigNumberish, t: BigNumberish];
  export type OutputTuple = [A: bigint, t: bigint];
  export interface OutputObject {
    A: bigint;
    t: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApplyNewFeeEvent {
  export type InputTuple = [
    fee: BigNumberish,
    offpeg_fee_multiplier: BigNumberish,
  ];
  export type OutputTuple = [fee: bigint, offpeg_fee_multiplier: bigint];
  export interface OutputObject {
    fee: bigint;
    offpeg_fee_multiplier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetNewMATimeEvent {
  export type InputTuple = [ma_exp_time: BigNumberish, D_ma_time: BigNumberish];
  export type OutputTuple = [ma_exp_time: bigint, D_ma_time: bigint];
  export interface OutputObject {
    ma_exp_time: bigint;
    D_ma_time: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CurveStableSwapNG extends BaseContract {
  connect(runner?: ContractRunner | null): CurveStableSwapNG;
  waitForDeployment(): Promise<this>;

  interface: CurveStableSwapNGInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  "exchange(int128,int128,uint256,uint256)": TypedContractMethod<
    [
      i: BigNumberish,
      j: BigNumberish,
      _dx: BigNumberish,
      _min_dy: BigNumberish,
    ],
    [bigint],
    "nonpayable"
  >;

  "exchange(int128,int128,uint256,uint256,address)": TypedContractMethod<
    [
      i: BigNumberish,
      j: BigNumberish,
      _dx: BigNumberish,
      _min_dy: BigNumberish,
      _receiver: AddressLike,
    ],
    [bigint],
    "nonpayable"
  >;

  "exchange_received(int128,int128,uint256,uint256)": TypedContractMethod<
    [
      i: BigNumberish,
      j: BigNumberish,
      _dx: BigNumberish,
      _min_dy: BigNumberish,
    ],
    [bigint],
    "nonpayable"
  >;

  "exchange_received(int128,int128,uint256,uint256,address)": TypedContractMethod<
    [
      i: BigNumberish,
      j: BigNumberish,
      _dx: BigNumberish,
      _min_dy: BigNumberish,
      _receiver: AddressLike,
    ],
    [bigint],
    "nonpayable"
  >;

  "add_liquidity(uint256[],uint256)": TypedContractMethod<
    [_amounts: BigNumberish[], _min_mint_amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  "add_liquidity(uint256[],uint256,address)": TypedContractMethod<
    [
      _amounts: BigNumberish[],
      _min_mint_amount: BigNumberish,
      _receiver: AddressLike,
    ],
    [bigint],
    "nonpayable"
  >;

  "remove_liquidity_one_coin(uint256,int128,uint256)": TypedContractMethod<
    [_burn_amount: BigNumberish, i: BigNumberish, _min_received: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  "remove_liquidity_one_coin(uint256,int128,uint256,address)": TypedContractMethod<
    [
      _burn_amount: BigNumberish,
      i: BigNumberish,
      _min_received: BigNumberish,
      _receiver: AddressLike,
    ],
    [bigint],
    "nonpayable"
  >;

  "remove_liquidity_imbalance(uint256[],uint256)": TypedContractMethod<
    [_amounts: BigNumberish[], _max_burn_amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  "remove_liquidity_imbalance(uint256[],uint256,address)": TypedContractMethod<
    [
      _amounts: BigNumberish[],
      _max_burn_amount: BigNumberish,
      _receiver: AddressLike,
    ],
    [bigint],
    "nonpayable"
  >;

  "remove_liquidity(uint256,uint256[])": TypedContractMethod<
    [_burn_amount: BigNumberish, _min_amounts: BigNumberish[]],
    [bigint[]],
    "nonpayable"
  >;

  "remove_liquidity(uint256,uint256[],address)": TypedContractMethod<
    [
      _burn_amount: BigNumberish,
      _min_amounts: BigNumberish[],
      _receiver: AddressLike,
    ],
    [bigint[]],
    "nonpayable"
  >;

  "remove_liquidity(uint256,uint256[],address,bool)": TypedContractMethod<
    [
      _burn_amount: BigNumberish,
      _min_amounts: BigNumberish[],
      _receiver: AddressLike,
      _claim_admin_fees: boolean,
    ],
    [bigint[]],
    "nonpayable"
  >;

  withdraw_admin_fees: TypedContractMethod<[], [void], "nonpayable">;

  last_price: TypedContractMethod<[i: BigNumberish], [bigint], "view">;

  ema_price: TypedContractMethod<[i: BigNumberish], [bigint], "view">;

  get_p: TypedContractMethod<[i: BigNumberish], [bigint], "view">;

  price_oracle: TypedContractMethod<[i: BigNumberish], [bigint], "view">;

  D_oracle: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [_to: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  approve: TypedContractMethod<
    [_spender: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  permit: TypedContractMethod<
    [
      _owner: AddressLike,
      _spender: AddressLike,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
    ],
    [boolean],
    "nonpayable"
  >;

  DOMAIN_SEPARATOR: TypedContractMethod<[], [string], "view">;

  get_dx: TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dy: BigNumberish],
    [bigint],
    "view"
  >;

  get_dy: TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish],
    [bigint],
    "view"
  >;

  calc_withdraw_one_coin: TypedContractMethod<
    [_burn_amount: BigNumberish, i: BigNumberish],
    [bigint],
    "view"
  >;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  get_virtual_price: TypedContractMethod<[], [bigint], "view">;

  calc_token_amount: TypedContractMethod<
    [_amounts: BigNumberish[], _is_deposit: boolean],
    [bigint],
    "view"
  >;

  A: TypedContractMethod<[], [bigint], "view">;

  A_precise: TypedContractMethod<[], [bigint], "view">;

  balances: TypedContractMethod<[i: BigNumberish], [bigint], "view">;

  get_balances: TypedContractMethod<[], [bigint[]], "view">;

  stored_rates: TypedContractMethod<[], [bigint[]], "view">;

  dynamic_fee: TypedContractMethod<
    [i: BigNumberish, j: BigNumberish],
    [bigint],
    "view"
  >;

  ramp_A: TypedContractMethod<
    [_future_A: BigNumberish, _future_time: BigNumberish],
    [void],
    "nonpayable"
  >;

  stop_ramp_A: TypedContractMethod<[], [void], "nonpayable">;

  set_new_fee: TypedContractMethod<
    [_new_fee: BigNumberish, _new_offpeg_fee_multiplier: BigNumberish],
    [void],
    "nonpayable"
  >;

  set_ma_exp_time: TypedContractMethod<
    [_ma_exp_time: BigNumberish, _D_ma_time: BigNumberish],
    [void],
    "nonpayable"
  >;

  N_COINS: TypedContractMethod<[], [bigint], "view">;

  coins: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  fee: TypedContractMethod<[], [bigint], "view">;

  offpeg_fee_multiplier: TypedContractMethod<[], [bigint], "view">;

  admin_fee: TypedContractMethod<[], [bigint], "view">;

  initial_A: TypedContractMethod<[], [bigint], "view">;

  future_A: TypedContractMethod<[], [bigint], "view">;

  initial_A_time: TypedContractMethod<[], [bigint], "view">;

  future_A_time: TypedContractMethod<[], [bigint], "view">;

  admin_balances: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  ma_exp_time: TypedContractMethod<[], [bigint], "view">;

  D_ma_time: TypedContractMethod<[], [bigint], "view">;

  ma_last_time: TypedContractMethod<[], [bigint], "view">;

  name: TypedContractMethod<[], [string], "view">;

  symbol: TypedContractMethod<[], [string], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  version: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  allowance: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  salt: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: "exchange(int128,int128,uint256,uint256)",
  ): TypedContractMethod<
    [
      i: BigNumberish,
      j: BigNumberish,
      _dx: BigNumberish,
      _min_dy: BigNumberish,
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exchange(int128,int128,uint256,uint256,address)",
  ): TypedContractMethod<
    [
      i: BigNumberish,
      j: BigNumberish,
      _dx: BigNumberish,
      _min_dy: BigNumberish,
      _receiver: AddressLike,
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exchange_received(int128,int128,uint256,uint256)",
  ): TypedContractMethod<
    [
      i: BigNumberish,
      j: BigNumberish,
      _dx: BigNumberish,
      _min_dy: BigNumberish,
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exchange_received(int128,int128,uint256,uint256,address)",
  ): TypedContractMethod<
    [
      i: BigNumberish,
      j: BigNumberish,
      _dx: BigNumberish,
      _min_dy: BigNumberish,
      _receiver: AddressLike,
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_liquidity(uint256[],uint256)",
  ): TypedContractMethod<
    [_amounts: BigNumberish[], _min_mint_amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_liquidity(uint256[],uint256,address)",
  ): TypedContractMethod<
    [
      _amounts: BigNumberish[],
      _min_mint_amount: BigNumberish,
      _receiver: AddressLike,
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remove_liquidity_one_coin(uint256,int128,uint256)",
  ): TypedContractMethod<
    [_burn_amount: BigNumberish, i: BigNumberish, _min_received: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remove_liquidity_one_coin(uint256,int128,uint256,address)",
  ): TypedContractMethod<
    [
      _burn_amount: BigNumberish,
      i: BigNumberish,
      _min_received: BigNumberish,
      _receiver: AddressLike,
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remove_liquidity_imbalance(uint256[],uint256)",
  ): TypedContractMethod<
    [_amounts: BigNumberish[], _max_burn_amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remove_liquidity_imbalance(uint256[],uint256,address)",
  ): TypedContractMethod<
    [
      _amounts: BigNumberish[],
      _max_burn_amount: BigNumberish,
      _receiver: AddressLike,
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remove_liquidity(uint256,uint256[])",
  ): TypedContractMethod<
    [_burn_amount: BigNumberish, _min_amounts: BigNumberish[]],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remove_liquidity(uint256,uint256[],address)",
  ): TypedContractMethod<
    [
      _burn_amount: BigNumberish,
      _min_amounts: BigNumberish[],
      _receiver: AddressLike,
    ],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remove_liquidity(uint256,uint256[],address,bool)",
  ): TypedContractMethod<
    [
      _burn_amount: BigNumberish,
      _min_amounts: BigNumberish[],
      _receiver: AddressLike,
      _claim_admin_fees: boolean,
    ],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw_admin_fees",
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "last_price",
  ): TypedContractMethod<[i: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "ema_price",
  ): TypedContractMethod<[i: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "get_p",
  ): TypedContractMethod<[i: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "price_oracle",
  ): TypedContractMethod<[i: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "D_oracle",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer",
  ): TypedContractMethod<
    [_to: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom",
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approve",
  ): TypedContractMethod<
    [_spender: AddressLike, _value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "permit",
  ): TypedContractMethod<
    [
      _owner: AddressLike,
      _spender: AddressLike,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "DOMAIN_SEPARATOR",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "get_dx",
  ): TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dy: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "get_dy",
  ): TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calc_withdraw_one_coin",
  ): TypedContractMethod<
    [_burn_amount: BigNumberish, i: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalSupply",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "get_virtual_price",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calc_token_amount",
  ): TypedContractMethod<
    [_amounts: BigNumberish[], _is_deposit: boolean],
    [bigint],
    "view"
  >;
  getFunction(nameOrSignature: "A"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "A_precise",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balances",
  ): TypedContractMethod<[i: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "get_balances",
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "stored_rates",
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "dynamic_fee",
  ): TypedContractMethod<[i: BigNumberish, j: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "ramp_A",
  ): TypedContractMethod<
    [_future_A: BigNumberish, _future_time: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stop_ramp_A",
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "set_new_fee",
  ): TypedContractMethod<
    [_new_fee: BigNumberish, _new_offpeg_fee_multiplier: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "set_ma_exp_time",
  ): TypedContractMethod<
    [_ma_exp_time: BigNumberish, _D_ma_time: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "N_COINS",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "coins",
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "fee",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "offpeg_fee_multiplier",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin_fee",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initial_A",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "future_A",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initial_A_time",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "future_A_time",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin_balances",
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "ma_exp_time",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "D_ma_time",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ma_last_time",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "name",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "symbol",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decimals",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "version",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf",
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "allowance",
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "nonces",
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "salt",
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Transfer",
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Approval",
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "TokenExchange",
  ): TypedContractEvent<
    TokenExchangeEvent.InputTuple,
    TokenExchangeEvent.OutputTuple,
    TokenExchangeEvent.OutputObject
  >;
  getEvent(
    key: "TokenExchangeUnderlying",
  ): TypedContractEvent<
    TokenExchangeUnderlyingEvent.InputTuple,
    TokenExchangeUnderlyingEvent.OutputTuple,
    TokenExchangeUnderlyingEvent.OutputObject
  >;
  getEvent(
    key: "AddLiquidity",
  ): TypedContractEvent<
    AddLiquidityEvent.InputTuple,
    AddLiquidityEvent.OutputTuple,
    AddLiquidityEvent.OutputObject
  >;
  getEvent(
    key: "RemoveLiquidity",
  ): TypedContractEvent<
    RemoveLiquidityEvent.InputTuple,
    RemoveLiquidityEvent.OutputTuple,
    RemoveLiquidityEvent.OutputObject
  >;
  getEvent(
    key: "RemoveLiquidityOne",
  ): TypedContractEvent<
    RemoveLiquidityOneEvent.InputTuple,
    RemoveLiquidityOneEvent.OutputTuple,
    RemoveLiquidityOneEvent.OutputObject
  >;
  getEvent(
    key: "RemoveLiquidityImbalance",
  ): TypedContractEvent<
    RemoveLiquidityImbalanceEvent.InputTuple,
    RemoveLiquidityImbalanceEvent.OutputTuple,
    RemoveLiquidityImbalanceEvent.OutputObject
  >;
  getEvent(
    key: "RampA",
  ): TypedContractEvent<
    RampAEvent.InputTuple,
    RampAEvent.OutputTuple,
    RampAEvent.OutputObject
  >;
  getEvent(
    key: "StopRampA",
  ): TypedContractEvent<
    StopRampAEvent.InputTuple,
    StopRampAEvent.OutputTuple,
    StopRampAEvent.OutputObject
  >;
  getEvent(
    key: "ApplyNewFee",
  ): TypedContractEvent<
    ApplyNewFeeEvent.InputTuple,
    ApplyNewFeeEvent.OutputTuple,
    ApplyNewFeeEvent.OutputObject
  >;
  getEvent(
    key: "SetNewMATime",
  ): TypedContractEvent<
    SetNewMATimeEvent.InputTuple,
    SetNewMATimeEvent.OutputTuple,
    SetNewMATimeEvent.OutputObject
  >;

  filters: {
    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "TokenExchange(address,int128,uint256,int128,uint256)": TypedContractEvent<
      TokenExchangeEvent.InputTuple,
      TokenExchangeEvent.OutputTuple,
      TokenExchangeEvent.OutputObject
    >;
    TokenExchange: TypedContractEvent<
      TokenExchangeEvent.InputTuple,
      TokenExchangeEvent.OutputTuple,
      TokenExchangeEvent.OutputObject
    >;

    "TokenExchangeUnderlying(address,int128,uint256,int128,uint256)": TypedContractEvent<
      TokenExchangeUnderlyingEvent.InputTuple,
      TokenExchangeUnderlyingEvent.OutputTuple,
      TokenExchangeUnderlyingEvent.OutputObject
    >;
    TokenExchangeUnderlying: TypedContractEvent<
      TokenExchangeUnderlyingEvent.InputTuple,
      TokenExchangeUnderlyingEvent.OutputTuple,
      TokenExchangeUnderlyingEvent.OutputObject
    >;

    "AddLiquidity(address,uint256[],uint256[],uint256,uint256)": TypedContractEvent<
      AddLiquidityEvent.InputTuple,
      AddLiquidityEvent.OutputTuple,
      AddLiquidityEvent.OutputObject
    >;
    AddLiquidity: TypedContractEvent<
      AddLiquidityEvent.InputTuple,
      AddLiquidityEvent.OutputTuple,
      AddLiquidityEvent.OutputObject
    >;

    "RemoveLiquidity(address,uint256[],uint256[],uint256)": TypedContractEvent<
      RemoveLiquidityEvent.InputTuple,
      RemoveLiquidityEvent.OutputTuple,
      RemoveLiquidityEvent.OutputObject
    >;
    RemoveLiquidity: TypedContractEvent<
      RemoveLiquidityEvent.InputTuple,
      RemoveLiquidityEvent.OutputTuple,
      RemoveLiquidityEvent.OutputObject
    >;

    "RemoveLiquidityOne(address,int128,uint256,uint256,uint256)": TypedContractEvent<
      RemoveLiquidityOneEvent.InputTuple,
      RemoveLiquidityOneEvent.OutputTuple,
      RemoveLiquidityOneEvent.OutputObject
    >;
    RemoveLiquidityOne: TypedContractEvent<
      RemoveLiquidityOneEvent.InputTuple,
      RemoveLiquidityOneEvent.OutputTuple,
      RemoveLiquidityOneEvent.OutputObject
    >;

    "RemoveLiquidityImbalance(address,uint256[],uint256[],uint256,uint256)": TypedContractEvent<
      RemoveLiquidityImbalanceEvent.InputTuple,
      RemoveLiquidityImbalanceEvent.OutputTuple,
      RemoveLiquidityImbalanceEvent.OutputObject
    >;
    RemoveLiquidityImbalance: TypedContractEvent<
      RemoveLiquidityImbalanceEvent.InputTuple,
      RemoveLiquidityImbalanceEvent.OutputTuple,
      RemoveLiquidityImbalanceEvent.OutputObject
    >;

    "RampA(uint256,uint256,uint256,uint256)": TypedContractEvent<
      RampAEvent.InputTuple,
      RampAEvent.OutputTuple,
      RampAEvent.OutputObject
    >;
    RampA: TypedContractEvent<
      RampAEvent.InputTuple,
      RampAEvent.OutputTuple,
      RampAEvent.OutputObject
    >;

    "StopRampA(uint256,uint256)": TypedContractEvent<
      StopRampAEvent.InputTuple,
      StopRampAEvent.OutputTuple,
      StopRampAEvent.OutputObject
    >;
    StopRampA: TypedContractEvent<
      StopRampAEvent.InputTuple,
      StopRampAEvent.OutputTuple,
      StopRampAEvent.OutputObject
    >;

    "ApplyNewFee(uint256,uint256)": TypedContractEvent<
      ApplyNewFeeEvent.InputTuple,
      ApplyNewFeeEvent.OutputTuple,
      ApplyNewFeeEvent.OutputObject
    >;
    ApplyNewFee: TypedContractEvent<
      ApplyNewFeeEvent.InputTuple,
      ApplyNewFeeEvent.OutputTuple,
      ApplyNewFeeEvent.OutputObject
    >;

    "SetNewMATime(uint256,uint256)": TypedContractEvent<
      SetNewMATimeEvent.InputTuple,
      SetNewMATimeEvent.OutputTuple,
      SetNewMATimeEvent.OutputObject
    >;
    SetNewMATime: TypedContractEvent<
      SetNewMATimeEvent.InputTuple,
      SetNewMATimeEvent.OutputTuple,
      SetNewMATimeEvent.OutputObject
    >;
  };
}
