export const cometAbi = [
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "governor", type: "address" },
          { internalType: "address", name: "pauseGuardian", type: "address" },
          { internalType: "address", name: "baseToken", type: "address" },
          {
            internalType: "address",
            name: "baseTokenPriceFeed",
            type: "address",
          },
          {
            internalType: "address",
            name: "extensionDelegate",
            type: "address",
          },
          { internalType: "uint64", name: "supplyKink", type: "uint64" },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateSlopeLow",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateSlopeHigh",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateBase",
            type: "uint64",
          },
          { internalType: "uint64", name: "borrowKink", type: "uint64" },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateSlopeLow",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateSlopeHigh",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateBase",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "storeFrontPriceFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "trackingIndexScale",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "baseTrackingSupplySpeed",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "baseTrackingBorrowSpeed",
            type: "uint64",
          },
          {
            internalType: "uint104",
            name: "baseMinForRewards",
            type: "uint104",
          },
          { internalType: "uint104", name: "baseBorrowMin", type: "uint104" },
          { internalType: "uint104", name: "targetReserves", type: "uint104" },
          {
            components: [
              { internalType: "address", name: "asset", type: "address" },
              { internalType: "address", name: "priceFeed", type: "address" },
              { internalType: "uint8", name: "decimals", type: "uint8" },
              {
                internalType: "uint64",
                name: "borrowCollateralFactor",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "liquidateCollateralFactor",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "liquidationFactor",
                type: "uint64",
              },
              { internalType: "uint128", name: "supplyCap", type: "uint128" },
            ],
            internalType: "struct CometConfiguration.AssetConfig[]",
            name: "assetConfigs",
            type: "tuple[]",
          },
        ],
        internalType: "struct CometConfiguration.Configuration",
        name: "config",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "Absurd", type: "error" },
  { inputs: [], name: "AlreadyInitialized", type: "error" },
  { inputs: [], name: "BadAsset", type: "error" },
  { inputs: [], name: "BadDecimals", type: "error" },
  { inputs: [], name: "BadDiscount", type: "error" },
  { inputs: [], name: "BadMinimum", type: "error" },
  { inputs: [], name: "BadPrice", type: "error" },
  { inputs: [], name: "BorrowCFTooLarge", type: "error" },
  { inputs: [], name: "BorrowTooSmall", type: "error" },
  { inputs: [], name: "InsufficientReserves", type: "error" },
  { inputs: [], name: "InvalidInt104", type: "error" },
  { inputs: [], name: "InvalidInt256", type: "error" },
  { inputs: [], name: "InvalidUInt104", type: "error" },
  { inputs: [], name: "InvalidUInt128", type: "error" },
  { inputs: [], name: "InvalidUInt64", type: "error" },
  { inputs: [], name: "LiquidateCFTooLarge", type: "error" },
  { inputs: [], name: "NegativeNumber", type: "error" },
  { inputs: [], name: "NoSelfTransfer", type: "error" },
  { inputs: [], name: "NotCollateralized", type: "error" },
  { inputs: [], name: "NotForSale", type: "error" },
  { inputs: [], name: "NotLiquidatable", type: "error" },
  { inputs: [], name: "Paused", type: "error" },
  { inputs: [], name: "SupplyCapExceeded", type: "error" },
  { inputs: [], name: "TimestampTooLarge", type: "error" },
  { inputs: [], name: "TooManyAssets", type: "error" },
  { inputs: [], name: "TooMuchSlippage", type: "error" },
  { inputs: [], name: "TransferInFailed", type: "error" },
  { inputs: [], name: "TransferOutFailed", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "absorber",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "collateralAbsorbed",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "usdValue",
        type: "uint256",
      },
    ],
    name: "AbsorbCollateral",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "absorber",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "basePaidOut",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "usdValue",
        type: "uint256",
      },
    ],
    name: "AbsorbDebt",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "baseAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "collateralAmount",
        type: "uint256",
      },
    ],
    name: "BuyCollateral",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool",
        name: "supplyPaused",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "transferPaused",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "withdrawPaused",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "absorbPaused",
        type: "bool",
      },
      { indexed: false, internalType: "bool", name: "buyPaused", type: "bool" },
    ],
    name: "PauseAction",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "dst", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Supply",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "dst", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "SupplyCollateral",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "TransferCollateral",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "src", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "src", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "WithdrawCollateral",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "WithdrawReserves",
    type: "event",
  },
  { stateMutability: "payable", type: "fallback" },
  {
    inputs: [
      { internalType: "address", name: "absorber", type: "address" },
      { internalType: "address[]", name: "accounts", type: "address[]" },
    ],
    name: "absorb",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "accrueAccount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "manager", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "approveThis",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "baseBorrowMin",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "baseMinForRewards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "baseScale",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "baseToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "baseTokenPriceFeed",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "baseTrackingBorrowSpeed",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "baseTrackingSupplySpeed",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "borrowBalanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "borrowKink",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "borrowPerSecondInterestRateBase",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "borrowPerSecondInterestRateSlopeHigh",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "borrowPerSecondInterestRateSlopeLow",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "minAmount", type: "uint256" },
      { internalType: "uint256", name: "baseAmount", type: "uint256" },
      { internalType: "address", name: "recipient", type: "address" },
    ],
    name: "buyCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "extensionDelegate",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "i", type: "uint8" }],
    name: "getAssetInfo",
    outputs: [
      {
        components: [
          { internalType: "uint8", name: "offset", type: "uint8" },
          { internalType: "address", name: "asset", type: "address" },
          { internalType: "address", name: "priceFeed", type: "address" },
          { internalType: "uint64", name: "scale", type: "uint64" },
          {
            internalType: "uint64",
            name: "borrowCollateralFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "liquidateCollateralFactor",
            type: "uint64",
          },
          { internalType: "uint64", name: "liquidationFactor", type: "uint64" },
          { internalType: "uint128", name: "supplyCap", type: "uint128" },
        ],
        internalType: "struct CometCore.AssetInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "asset", type: "address" }],
    name: "getAssetInfoByAddress",
    outputs: [
      {
        components: [
          { internalType: "uint8", name: "offset", type: "uint8" },
          { internalType: "address", name: "asset", type: "address" },
          { internalType: "address", name: "priceFeed", type: "address" },
          { internalType: "uint64", name: "scale", type: "uint64" },
          {
            internalType: "uint64",
            name: "borrowCollateralFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "liquidateCollateralFactor",
            type: "uint64",
          },
          { internalType: "uint64", name: "liquidationFactor", type: "uint64" },
          { internalType: "uint128", name: "supplyCap", type: "uint128" },
        ],
        internalType: "struct CometCore.AssetInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "utilization", type: "uint256" }],
    name: "getBorrowRate",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "asset", type: "address" }],
    name: "getCollateralReserves",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "priceFeed", type: "address" }],
    name: "getPrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getReserves",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "utilization", type: "uint256" }],
    name: "getSupplyRate",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getUtilization",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "governor",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "manager", type: "address" },
    ],
    name: "hasPermission",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initializeStorage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "isAbsorbPaused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "isAllowed",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "isBorrowCollateralized",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isBuyPaused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "isLiquidatable",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isSupplyPaused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isTransferPaused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isWithdrawPaused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "liquidatorPoints",
    outputs: [
      { internalType: "uint32", name: "numAbsorbs", type: "uint32" },
      { internalType: "uint64", name: "numAbsorbed", type: "uint64" },
      { internalType: "uint128", name: "approxSpend", type: "uint128" },
      { internalType: "uint32", name: "_reserved", type: "uint32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "numAssets",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bool", name: "supplyPaused", type: "bool" },
      { internalType: "bool", name: "transferPaused", type: "bool" },
      { internalType: "bool", name: "withdrawPaused", type: "bool" },
      { internalType: "bool", name: "absorbPaused", type: "bool" },
      { internalType: "bool", name: "buyPaused", type: "bool" },
    ],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pauseGuardian",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "baseAmount", type: "uint256" },
    ],
    name: "quoteCollateral",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "storeFrontPriceFactor",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "supply",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "dst", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "supplyFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "supplyKink",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "supplyPerSecondInterestRateBase",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "supplyPerSecondInterestRateSlopeHigh",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "supplyPerSecondInterestRateSlopeLow",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "dst", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "supplyTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "targetReserves",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalBorrow",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "totalsCollateral",
    outputs: [
      { internalType: "uint128", name: "totalSupplyAsset", type: "uint128" },
      { internalType: "uint128", name: "_reserved", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "trackingIndexScale",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "dst", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "dst", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transferAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "src", type: "address" },
      { internalType: "address", name: "dst", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transferAssetFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "src", type: "address" },
      { internalType: "address", name: "dst", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userBasic",
    outputs: [
      { internalType: "int104", name: "principal", type: "int104" },
      { internalType: "uint64", name: "baseTrackingIndex", type: "uint64" },
      { internalType: "uint64", name: "baseTrackingAccrued", type: "uint64" },
      { internalType: "uint16", name: "assetsIn", type: "uint16" },
      { internalType: "uint8", name: "_reserved", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "userCollateral",
    outputs: [
      { internalType: "uint128", name: "balance", type: "uint128" },
      { internalType: "uint128", name: "_reserved", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userNonce",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "src", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "withdrawFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "withdrawReserves",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "withdrawTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export const cometExtAbi = [
  {
    inputs: [
      {
        components: [
          { internalType: "bytes32", name: "name32", type: "bytes32" },
          { internalType: "bytes32", name: "symbol32", type: "bytes32" },
        ],
        internalType: "struct CometConfiguration.ExtConfiguration",
        name: "config",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "BadAmount", type: "error" },
  { inputs: [], name: "BadNonce", type: "error" },
  { inputs: [], name: "BadSignatory", type: "error" },
  { inputs: [], name: "InvalidInt104", type: "error" },
  { inputs: [], name: "InvalidInt256", type: "error" },
  { inputs: [], name: "InvalidUInt104", type: "error" },
  { inputs: [], name: "InvalidUInt128", type: "error" },
  { inputs: [], name: "InvalidUInt64", type: "error" },
  { inputs: [], name: "InvalidValueS", type: "error" },
  { inputs: [], name: "InvalidValueV", type: "error" },
  { inputs: [], name: "NegativeNumber", type: "error" },
  { inputs: [], name: "SignatureExpired", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "manager", type: "address" },
      { internalType: "bool", name: "isAllowed_", type: "bool" },
    ],
    name: "allow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "manager", type: "address" },
      { internalType: "bool", name: "isAllowed_", type: "bool" },
      { internalType: "uint256", name: "nonce", type: "uint256" },
      { internalType: "uint256", name: "expiry", type: "uint256" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "allowBySig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "baseAccrualScale",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "baseIndexScale",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "baseTrackingAccrued",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
    ],
    name: "collateralBalanceOf",
    outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "factorScale",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "manager", type: "address" },
    ],
    name: "hasPermission",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "isAllowed",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "liquidatorPoints",
    outputs: [
      { internalType: "uint32", name: "numAbsorbs", type: "uint32" },
      { internalType: "uint64", name: "numAbsorbed", type: "uint64" },
      { internalType: "uint128", name: "approxSpend", type: "uint128" },
      { internalType: "uint32", name: "_reserved", type: "uint32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxAssets",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "priceScale",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalsBasic",
    outputs: [
      {
        components: [
          { internalType: "uint64", name: "baseSupplyIndex", type: "uint64" },
          { internalType: "uint64", name: "baseBorrowIndex", type: "uint64" },
          {
            internalType: "uint64",
            name: "trackingSupplyIndex",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "trackingBorrowIndex",
            type: "uint64",
          },
          { internalType: "uint104", name: "totalSupplyBase", type: "uint104" },
          { internalType: "uint104", name: "totalBorrowBase", type: "uint104" },
          { internalType: "uint40", name: "lastAccrualTime", type: "uint40" },
          { internalType: "uint8", name: "pauseFlags", type: "uint8" },
        ],
        internalType: "struct CometStorage.TotalsBasic",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "totalsCollateral",
    outputs: [
      { internalType: "uint128", name: "totalSupplyAsset", type: "uint128" },
      { internalType: "uint128", name: "_reserved", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userBasic",
    outputs: [
      { internalType: "int104", name: "principal", type: "int104" },
      { internalType: "uint64", name: "baseTrackingIndex", type: "uint64" },
      { internalType: "uint64", name: "baseTrackingAccrued", type: "uint64" },
      { internalType: "uint16", name: "assetsIn", type: "uint16" },
      { internalType: "uint8", name: "_reserved", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "userCollateral",
    outputs: [
      { internalType: "uint128", name: "balance", type: "uint128" },
      { internalType: "uint128", name: "_reserved", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userNonce",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const configuratorAbi = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "AlreadyInitialized", type: "error" },
  { inputs: [], name: "AssetDoesNotExist", type: "error" },
  { inputs: [], name: "ConfigurationAlreadyExists", type: "error" },
  { inputs: [], name: "InvalidAddress", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        components: [
          { internalType: "address", name: "asset", type: "address" },
          { internalType: "address", name: "priceFeed", type: "address" },
          { internalType: "uint8", name: "decimals", type: "uint8" },
          {
            internalType: "uint64",
            name: "borrowCollateralFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "liquidateCollateralFactor",
            type: "uint64",
          },
          { internalType: "uint64", name: "liquidationFactor", type: "uint64" },
          { internalType: "uint128", name: "supplyCap", type: "uint128" },
        ],
        indexed: false,
        internalType: "struct CometConfiguration.AssetConfig",
        name: "assetConfig",
        type: "tuple",
      },
    ],
    name: "AddAsset",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newComet",
        type: "address",
      },
    ],
    name: "CometDeployed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldGovernor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newGovernor",
        type: "address",
      },
    ],
    name: "GovernorTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint104",
        name: "oldBaseBorrowMin",
        type: "uint104",
      },
      {
        indexed: false,
        internalType: "uint104",
        name: "newBaseBorrowMin",
        type: "uint104",
      },
    ],
    name: "SetBaseBorrowMin",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint104",
        name: "oldBaseMinForRewards",
        type: "uint104",
      },
      {
        indexed: false,
        internalType: "uint104",
        name: "newBaseMinForRewards",
        type: "uint104",
      },
    ],
    name: "SetBaseMinForRewards",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "oldBaseTokenPriceFeed",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newBaseTokenPriceFeed",
        type: "address",
      },
    ],
    name: "SetBaseTokenPriceFeed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldBaseTrackingBorrowSpeed",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newBaseTrackingBorrowSpeed",
        type: "uint64",
      },
    ],
    name: "SetBaseTrackingBorrowSpeed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldBaseTrackingSupplySpeed",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newBaseTrackingSupplySpeed",
        type: "uint64",
      },
    ],
    name: "SetBaseTrackingSupplySpeed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldKink",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newKink",
        type: "uint64",
      },
    ],
    name: "SetBorrowKink",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldIRBase",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newIRBase",
        type: "uint64",
      },
    ],
    name: "SetBorrowPerYearInterestRateBase",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldIRSlopeHigh",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newIRSlopeHigh",
        type: "uint64",
      },
    ],
    name: "SetBorrowPerYearInterestRateSlopeHigh",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldIRSlopeLow",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newIRSlopeLow",
        type: "uint64",
      },
    ],
    name: "SetBorrowPerYearInterestRateSlopeLow",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        components: [
          { internalType: "address", name: "governor", type: "address" },
          { internalType: "address", name: "pauseGuardian", type: "address" },
          { internalType: "address", name: "baseToken", type: "address" },
          {
            internalType: "address",
            name: "baseTokenPriceFeed",
            type: "address",
          },
          {
            internalType: "address",
            name: "extensionDelegate",
            type: "address",
          },
          { internalType: "uint64", name: "supplyKink", type: "uint64" },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateSlopeLow",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateSlopeHigh",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateBase",
            type: "uint64",
          },
          { internalType: "uint64", name: "borrowKink", type: "uint64" },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateSlopeLow",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateSlopeHigh",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateBase",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "storeFrontPriceFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "trackingIndexScale",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "baseTrackingSupplySpeed",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "baseTrackingBorrowSpeed",
            type: "uint64",
          },
          {
            internalType: "uint104",
            name: "baseMinForRewards",
            type: "uint104",
          },
          { internalType: "uint104", name: "baseBorrowMin", type: "uint104" },
          { internalType: "uint104", name: "targetReserves", type: "uint104" },
          {
            components: [
              { internalType: "address", name: "asset", type: "address" },
              { internalType: "address", name: "priceFeed", type: "address" },
              { internalType: "uint8", name: "decimals", type: "uint8" },
              {
                internalType: "uint64",
                name: "borrowCollateralFactor",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "liquidateCollateralFactor",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "liquidationFactor",
                type: "uint64",
              },
              { internalType: "uint128", name: "supplyCap", type: "uint128" },
            ],
            internalType: "struct CometConfiguration.AssetConfig[]",
            name: "assetConfigs",
            type: "tuple[]",
          },
        ],
        indexed: false,
        internalType: "struct CometConfiguration.Configuration",
        name: "oldConfiguration",
        type: "tuple",
      },
      {
        components: [
          { internalType: "address", name: "governor", type: "address" },
          { internalType: "address", name: "pauseGuardian", type: "address" },
          { internalType: "address", name: "baseToken", type: "address" },
          {
            internalType: "address",
            name: "baseTokenPriceFeed",
            type: "address",
          },
          {
            internalType: "address",
            name: "extensionDelegate",
            type: "address",
          },
          { internalType: "uint64", name: "supplyKink", type: "uint64" },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateSlopeLow",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateSlopeHigh",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateBase",
            type: "uint64",
          },
          { internalType: "uint64", name: "borrowKink", type: "uint64" },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateSlopeLow",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateSlopeHigh",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateBase",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "storeFrontPriceFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "trackingIndexScale",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "baseTrackingSupplySpeed",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "baseTrackingBorrowSpeed",
            type: "uint64",
          },
          {
            internalType: "uint104",
            name: "baseMinForRewards",
            type: "uint104",
          },
          { internalType: "uint104", name: "baseBorrowMin", type: "uint104" },
          { internalType: "uint104", name: "targetReserves", type: "uint104" },
          {
            components: [
              { internalType: "address", name: "asset", type: "address" },
              { internalType: "address", name: "priceFeed", type: "address" },
              { internalType: "uint8", name: "decimals", type: "uint8" },
              {
                internalType: "uint64",
                name: "borrowCollateralFactor",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "liquidateCollateralFactor",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "liquidationFactor",
                type: "uint64",
              },
              { internalType: "uint128", name: "supplyCap", type: "uint128" },
            ],
            internalType: "struct CometConfiguration.AssetConfig[]",
            name: "assetConfigs",
            type: "tuple[]",
          },
        ],
        indexed: false,
        internalType: "struct CometConfiguration.Configuration",
        name: "newConfiguration",
        type: "tuple",
      },
    ],
    name: "SetConfiguration",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "oldExt",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newExt",
        type: "address",
      },
    ],
    name: "SetExtensionDelegate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "oldFactory",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newFactory",
        type: "address",
      },
    ],
    name: "SetFactory",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "oldGovernor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newGovernor",
        type: "address",
      },
    ],
    name: "SetGovernor",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "oldPauseGuardian",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newPauseGuardian",
        type: "address",
      },
    ],
    name: "SetPauseGuardian",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldStoreFrontPriceFactor",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newStoreFrontPriceFactor",
        type: "uint64",
      },
    ],
    name: "SetStoreFrontPriceFactor",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldKink",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newKink",
        type: "uint64",
      },
    ],
    name: "SetSupplyKink",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldIRBase",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newIRBase",
        type: "uint64",
      },
    ],
    name: "SetSupplyPerYearInterestRateBase",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldIRSlopeHigh",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newIRSlopeHigh",
        type: "uint64",
      },
    ],
    name: "SetSupplyPerYearInterestRateSlopeHigh",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldIRSlopeLow",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newIRSlopeLow",
        type: "uint64",
      },
    ],
    name: "SetSupplyPerYearInterestRateSlopeLow",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint104",
        name: "oldTargetReserves",
        type: "uint104",
      },
      {
        indexed: false,
        internalType: "uint104",
        name: "newTargetReserves",
        type: "uint104",
      },
    ],
    name: "SetTargetReserves",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        components: [
          { internalType: "address", name: "asset", type: "address" },
          { internalType: "address", name: "priceFeed", type: "address" },
          { internalType: "uint8", name: "decimals", type: "uint8" },
          {
            internalType: "uint64",
            name: "borrowCollateralFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "liquidateCollateralFactor",
            type: "uint64",
          },
          { internalType: "uint64", name: "liquidationFactor", type: "uint64" },
          { internalType: "uint128", name: "supplyCap", type: "uint128" },
        ],
        indexed: false,
        internalType: "struct CometConfiguration.AssetConfig",
        name: "oldAssetConfig",
        type: "tuple",
      },
      {
        components: [
          { internalType: "address", name: "asset", type: "address" },
          { internalType: "address", name: "priceFeed", type: "address" },
          { internalType: "uint8", name: "decimals", type: "uint8" },
          {
            internalType: "uint64",
            name: "borrowCollateralFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "liquidateCollateralFactor",
            type: "uint64",
          },
          { internalType: "uint64", name: "liquidationFactor", type: "uint64" },
          { internalType: "uint128", name: "supplyCap", type: "uint128" },
        ],
        indexed: false,
        internalType: "struct CometConfiguration.AssetConfig",
        name: "newAssetConfig",
        type: "tuple",
      },
    ],
    name: "UpdateAsset",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldBorrowCF",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newBorrowCF",
        type: "uint64",
      },
    ],
    name: "UpdateAssetBorrowCollateralFactor",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldLiquidateCF",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newLiquidateCF",
        type: "uint64",
      },
    ],
    name: "UpdateAssetLiquidateCollateralFactor",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "oldLiquidationFactor",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "newLiquidationFactor",
        type: "uint64",
      },
    ],
    name: "UpdateAssetLiquidationFactor",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "oldPriceFeed",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newPriceFeed",
        type: "address",
      },
    ],
    name: "UpdateAssetPriceFeed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "cometProxy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "oldSupplyCap",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "newSupplyCap",
        type: "uint128",
      },
    ],
    name: "UpdateAssetSupplyCap",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      {
        components: [
          { internalType: "address", name: "asset", type: "address" },
          { internalType: "address", name: "priceFeed", type: "address" },
          { internalType: "uint8", name: "decimals", type: "uint8" },
          {
            internalType: "uint64",
            name: "borrowCollateralFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "liquidateCollateralFactor",
            type: "uint64",
          },
          { internalType: "uint64", name: "liquidationFactor", type: "uint64" },
          { internalType: "uint128", name: "supplyCap", type: "uint128" },
        ],
        internalType: "struct CometConfiguration.AssetConfig",
        name: "assetConfig",
        type: "tuple",
      },
    ],
    name: "addAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "cometProxy", type: "address" }],
    name: "deploy",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "factory",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
    ],
    name: "getAssetIndex",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "cometProxy", type: "address" }],
    name: "getConfiguration",
    outputs: [
      {
        components: [
          { internalType: "address", name: "governor", type: "address" },
          { internalType: "address", name: "pauseGuardian", type: "address" },
          { internalType: "address", name: "baseToken", type: "address" },
          {
            internalType: "address",
            name: "baseTokenPriceFeed",
            type: "address",
          },
          {
            internalType: "address",
            name: "extensionDelegate",
            type: "address",
          },
          { internalType: "uint64", name: "supplyKink", type: "uint64" },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateSlopeLow",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateSlopeHigh",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateBase",
            type: "uint64",
          },
          { internalType: "uint64", name: "borrowKink", type: "uint64" },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateSlopeLow",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateSlopeHigh",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateBase",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "storeFrontPriceFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "trackingIndexScale",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "baseTrackingSupplySpeed",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "baseTrackingBorrowSpeed",
            type: "uint64",
          },
          {
            internalType: "uint104",
            name: "baseMinForRewards",
            type: "uint104",
          },
          { internalType: "uint104", name: "baseBorrowMin", type: "uint104" },
          { internalType: "uint104", name: "targetReserves", type: "uint104" },
          {
            components: [
              { internalType: "address", name: "asset", type: "address" },
              { internalType: "address", name: "priceFeed", type: "address" },
              { internalType: "uint8", name: "decimals", type: "uint8" },
              {
                internalType: "uint64",
                name: "borrowCollateralFactor",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "liquidateCollateralFactor",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "liquidationFactor",
                type: "uint64",
              },
              { internalType: "uint128", name: "supplyCap", type: "uint128" },
            ],
            internalType: "struct CometConfiguration.AssetConfig[]",
            name: "assetConfigs",
            type: "tuple[]",
          },
        ],
        internalType: "struct CometConfiguration.Configuration",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "governor",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "governor_", type: "address" }],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "uint104", name: "newBaseBorrowMin", type: "uint104" },
    ],
    name: "setBaseBorrowMin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      {
        internalType: "uint104",
        name: "newBaseMinForRewards",
        type: "uint104",
      },
    ],
    name: "setBaseMinForRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      {
        internalType: "address",
        name: "newBaseTokenPriceFeed",
        type: "address",
      },
    ],
    name: "setBaseTokenPriceFeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      {
        internalType: "uint64",
        name: "newBaseTrackingBorrowSpeed",
        type: "uint64",
      },
    ],
    name: "setBaseTrackingBorrowSpeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      {
        internalType: "uint64",
        name: "newBaseTrackingSupplySpeed",
        type: "uint64",
      },
    ],
    name: "setBaseTrackingSupplySpeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "uint64", name: "newBorrowKink", type: "uint64" },
    ],
    name: "setBorrowKink",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "uint64", name: "newBase", type: "uint64" },
    ],
    name: "setBorrowPerYearInterestRateBase",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "uint64", name: "newSlope", type: "uint64" },
    ],
    name: "setBorrowPerYearInterestRateSlopeHigh",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "uint64", name: "newSlope", type: "uint64" },
    ],
    name: "setBorrowPerYearInterestRateSlopeLow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      {
        components: [
          { internalType: "address", name: "governor", type: "address" },
          { internalType: "address", name: "pauseGuardian", type: "address" },
          { internalType: "address", name: "baseToken", type: "address" },
          {
            internalType: "address",
            name: "baseTokenPriceFeed",
            type: "address",
          },
          {
            internalType: "address",
            name: "extensionDelegate",
            type: "address",
          },
          { internalType: "uint64", name: "supplyKink", type: "uint64" },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateSlopeLow",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateSlopeHigh",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supplyPerYearInterestRateBase",
            type: "uint64",
          },
          { internalType: "uint64", name: "borrowKink", type: "uint64" },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateSlopeLow",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateSlopeHigh",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "borrowPerYearInterestRateBase",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "storeFrontPriceFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "trackingIndexScale",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "baseTrackingSupplySpeed",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "baseTrackingBorrowSpeed",
            type: "uint64",
          },
          {
            internalType: "uint104",
            name: "baseMinForRewards",
            type: "uint104",
          },
          { internalType: "uint104", name: "baseBorrowMin", type: "uint104" },
          { internalType: "uint104", name: "targetReserves", type: "uint104" },
          {
            components: [
              { internalType: "address", name: "asset", type: "address" },
              { internalType: "address", name: "priceFeed", type: "address" },
              { internalType: "uint8", name: "decimals", type: "uint8" },
              {
                internalType: "uint64",
                name: "borrowCollateralFactor",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "liquidateCollateralFactor",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "liquidationFactor",
                type: "uint64",
              },
              { internalType: "uint128", name: "supplyCap", type: "uint128" },
            ],
            internalType: "struct CometConfiguration.AssetConfig[]",
            name: "assetConfigs",
            type: "tuple[]",
          },
        ],
        internalType: "struct CometConfiguration.Configuration",
        name: "newConfiguration",
        type: "tuple",
      },
    ],
    name: "setConfiguration",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      {
        internalType: "address",
        name: "newExtensionDelegate",
        type: "address",
      },
    ],
    name: "setExtensionDelegate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "address", name: "newFactory", type: "address" },
    ],
    name: "setFactory",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "address", name: "newGovernor", type: "address" },
    ],
    name: "setGovernor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "address", name: "newPauseGuardian", type: "address" },
    ],
    name: "setPauseGuardian",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      {
        internalType: "uint64",
        name: "newStoreFrontPriceFactor",
        type: "uint64",
      },
    ],
    name: "setStoreFrontPriceFactor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "uint64", name: "newSupplyKink", type: "uint64" },
    ],
    name: "setSupplyKink",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "uint64", name: "newBase", type: "uint64" },
    ],
    name: "setSupplyPerYearInterestRateBase",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "uint64", name: "newSlope", type: "uint64" },
    ],
    name: "setSupplyPerYearInterestRateSlopeHigh",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "uint64", name: "newSlope", type: "uint64" },
    ],
    name: "setSupplyPerYearInterestRateSlopeLow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "uint104", name: "newTargetReserves", type: "uint104" },
    ],
    name: "setTargetReserves",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newGovernor", type: "address" }],
    name: "transferGovernor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      {
        components: [
          { internalType: "address", name: "asset", type: "address" },
          { internalType: "address", name: "priceFeed", type: "address" },
          { internalType: "uint8", name: "decimals", type: "uint8" },
          {
            internalType: "uint64",
            name: "borrowCollateralFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "liquidateCollateralFactor",
            type: "uint64",
          },
          { internalType: "uint64", name: "liquidationFactor", type: "uint64" },
          { internalType: "uint128", name: "supplyCap", type: "uint128" },
        ],
        internalType: "struct CometConfiguration.AssetConfig",
        name: "newAssetConfig",
        type: "tuple",
      },
    ],
    name: "updateAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint64", name: "newBorrowCF", type: "uint64" },
    ],
    name: "updateAssetBorrowCollateralFactor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint64", name: "newLiquidateCF", type: "uint64" },
    ],
    name: "updateAssetLiquidateCollateralFactor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint64", name: "newLiquidationFactor", type: "uint64" },
    ],
    name: "updateAssetLiquidationFactor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "address", name: "newPriceFeed", type: "address" },
    ],
    name: "updateAssetPriceFeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "cometProxy", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint128", name: "newSupplyCap", type: "uint128" },
    ],
    name: "updateAssetSupplyCap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
