// Generated by scripts/sync-version.mjs. Do not edit by hand.

/**
 * Exact package version sent to the Midnight router through the `sdk-version`
 * request header.
 *
 * @example
 * ```ts
 * import { MIDNIGHT_SDK_VERSION } from "@morpho-org/midnight-sdk";
 *
 * console.log(MIDNIGHT_SDK_VERSION);
 * ```
 */
export const MIDNIGHT_SDK_VERSION = "0.0.0";
