import { readFile, writeFile } from "node:fs/promises";

const packageJsonUrl = new URL("../package.json", import.meta.url);
const versionSourceUrl = new URL("../src/version.ts", import.meta.url);

const packageJson = JSON.parse(await readFile(packageJsonUrl, "utf8"));
const { version } = packageJson;

if (typeof version !== "string" || version.length === 0) {
  throw new Error(
    'packages/midnight-sdk/package.json must include a non-empty "version".',
  );
}

const source = `// Generated by scripts/sync-version.mjs. Do not edit by hand.

/**
 * Exact package version sent to the Midnight router through the \`sdk-version\`
 * request header.
 *
 * @example
 * \`\`\`ts
 * import { MIDNIGHT_SDK_VERSION } from "@morpho-org/midnight-sdk";
 *
 * console.log(MIDNIGHT_SDK_VERSION);
 * \`\`\`
 */
export const MIDNIGHT_SDK_VERSION = ${JSON.stringify(version)};
`;

const current = await readFile(versionSourceUrl, "utf8").catch(() => undefined);
if (current !== source) {
  await writeFile(versionSourceUrl, source);
}
