name: Build

on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package:
          - test
          - test-wagmi

          - morpho-ts
          - morpho-test

          - blue-sdk
          - blue-sdk-viem
          - blue-sdk-wagmi

          - simulation-sdk
          - simulation-sdk-wagmi

          - bundler-sdk-viem

          - liquidation-sdk-viem
          - liquidity-sdk-viem

          - migration-sdk-viem

    name: "@morpho-org/${{ matrix.package }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm --filter @morpho-org/${{ matrix.package }} build
