name: Push

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint:
    permissions:
      contents: read

    uses: ./.github/workflows/lint.yml

  build:
    permissions:
      contents: read

    uses: ./.github/workflows/build.yml

  test:
    permissions:
      contents: read

    uses: ./.github/workflows/test.yml
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
      ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
