name: Test

on:
  workflow_call:
    secrets:
      MAINNET_RPC_URL:
        required: true

jobs:
  vitest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Restore Foundry cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.foundry/cache/rpc
          key: foundry-${{ github.job }}-${{ github.sha }}
          restore-keys: foundry-${{ github.job }}-

      - uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1
        with:
          cache: false # Disable built-in cache to always save it.

      - run: pnpm install --frozen-lockfile

      - run: pnpm run test --coverage
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
          ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
          IS_LOGGING_DISABLED: true

      - name: Save Foundry cache
        if: always()
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.foundry/cache/rpc
          key: foundry-${{ github.job }}-${{ github.sha }}
